site_name: cog
site_author: Chris Choi
repo_url: https://github.com/chutsu/cog

pages:
- Home: index.md
- API:
    - darray: api/darray.md
    - hashmap: api/hashmap.md
    - list: api/list.md
    - munit: api/munit.md
    - stack: api/stack.md
    - utils: api/utils.md

theme: readthedocs
